Euler's Method

In [1]:
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
x = np.loadtxt(r"C:\Users\ANKIT MISHRA\Documents\gh.txt")

In [18]:
x

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [16]:
x[]

array([[3., 4.],
       [5., 6.],
       [7., 8.]])